import type { Competition } from "@/types";

export const COMPETITIONS: Competition[] = [
  {
    code: "PL",
    name: "Premier League",
    country: "England",
    emblem: "https://crests.football-data.org/PL.png",
    format: "league",
    tiebreaker: "epl",
    season: { startYear: 2025, label: "2025/26" },
    bands: [
      { positions: [1, 2, 3, 4], label: "Champions League", color: "ucl" },
      { positions: [5, 6],        label: "Europa League",    color: "uel" },
      { positions: [7],           label: "Conference League",color: "uecl" },
      { positions: [18, 19, 20],  label: "Relegation",       color: "relegation" },
    ],
  },
  {
    code: "PD",
    name: "La Liga",
    country: "Spain",
    emblem: "https://crests.football-data.org/PD.png",
    format: "league",
    tiebreaker: "laLiga",
    season: { startYear: 2025, label: "2025/26" },
    bands: [
      { positions: [1, 2, 3, 4], label: "Champions League", color: "ucl" },
      { positions: [5, 6],        label: "Europa League",    color: "uel" },
      { positions: [7],           label: "Conference League",color: "uecl" },
      { positions: [18, 19, 20],  label: "Relegation",       color: "relegation" },
    ],
  },
  {
    code: "BL1",
    name: "Bundesliga",
    country: "Germany",
    emblem: "https://crests.football-data.org/BL1.png",
    format: "league",
    tiebreaker: "bundesliga",
    season: { startYear: 2025, label: "2025/26" },
    bands: [
      { positions: [1, 2, 3, 4], label: "Champions League", color: "ucl" },
      { positions: [5, 6],        label: "Europa League",    color: "uel" },
      { positions: [7],           label: "Conference League",color: "uecl" },
      { positions: [16],          label: "Relegation playoff", color: "playoff" },
      { positions: [17, 18],      label: "Relegation",       color: "relegation" },
    ],
  },
  {
    code: "SA",
    name: "Serie A",
    country: "Italy",
    emblem: "https://crests.football-data.org/SA.png",
    format: "league",
    tiebreaker: "serieA",
    season: { startYear: 2025, label: "2025/26" },
    bands: [
      { positions: [1, 2, 3, 4], label: "Champions League", color: "ucl" },
      { positions: [5, 6],        label: "Europa League",    color: "uel" },
      { positions: [7],           label: "Conference League",color: "uecl" },
      { positions: [18, 19, 20],  label: "Relegation",       color: "relegation" },
    ],
  },
  {
    code: "FL1",
    name: "Ligue 1",
    country: "France",
    emblem: "https://crests.football-data.org/FL1.png",
    format: "league",
    tiebreaker: "ligue1",
    season: { startYear: 2025, label: "2025/26" },
    bands: [
      { positions: [1, 2, 3],    label: "Champions League", color: "ucl" },
      { positions: [4, 5],        label: "Europa League",    color: "uel" },
      { positions: [6],           label: "Conference League",color: "uecl" },
      { positions: [16],          label: "Relegation playoff", color: "playoff" },
      { positions: [17, 18],      label: "Relegation",       color: "relegation" },
    ],
  },
  {
    code: "DED",
    name: "Eredivisie",
    country: "Netherlands",
    emblem: "https://crests.football-data.org/DED.png",
    format: "league",
    tiebreaker: "eredivisie",
    season: { startYear: 2025, label: "2025/26" },
    bands: [
      { positions: [1, 2],    label: "Champions League", color: "ucl" },
      { positions: [3, 4],    label: "Europa League",    color: "uel" },
      { positions: [5, 6, 7], label: "Conference League",color: "uecl" },
      { positions: [17],      label: "Relegation playoff", color: "playoff" },
      { positions: [18],      label: "Relegation",       color: "relegation" },
    ],
  },
  {
    code: "PPL",
    name: "Primeira Liga",
    country: "Portugal",
    emblem: "https://crests.football-data.org/PPL.png",
    format: "league",
    tiebreaker: "primeira",
    season: { startYear: 2025, label: "2025/26" },
    bands: [
      { positions: [1, 2],    label: "Champions League", color: "ucl" },
      { positions: [3, 4],    label: "Europa League",    color: "uel" },
      { positions: [5],       label: "Conference League",color: "uecl" },
      { positions: [17, 18],  label: "Relegation",       color: "relegation" },
    ],
  },
  {
    code: "ELC",
    name: "Championship",
    country: "England",
    emblem: "https://crests.football-data.org/ELC.png",
    format: "league",
    tiebreaker: "championship",
    season: { startYear: 2025, label: "2025/26" },
    bands: [
      { positions: [1, 2],          label: "Promotion to Premier League", color: "promotion" },
      { positions: [3, 4, 5, 6],    label: "Playoff for promotion",       color: "playoff" },
      { positions: [22, 23, 24],    label: "Relegation",                  color: "relegation" },
    ],
  },
  {
    code: "BSA",
    name: "Brasileirão",
    country: "Brazil",
    emblem: "https://crests.football-data.org/BSA.png",
    format: "league",
    tiebreaker: "brasileirao",
    season: { startYear: 2025, label: "2025" },
    bands: [
      { positions: [1, 2, 3, 4, 5, 6], label: "Copa Libertadores",  color: "ucl" },
      { positions: [7, 8, 9, 10, 11, 12], label: "Copa Sudamericana", color: "uel" },
      { positions: [17, 18, 19, 20],   label: "Relegation",         color: "relegation" },
    ],
  },
];

export function getCompetition(code: string): Competition | undefined {
  return COMPETITIONS.find((c) => c.code === code);
}
