import type { BracketTemplate } from "@/types";

// ──────────────────────────────────────────────────────────────────────────
// 2026 FIFA World Cup — official knockout structure (12 groups of 4; the top
// two of each group plus the eight best third-placed teams reach the round of
// 32). Source: FIFA 2026 regulations Annex C, mirrored by the Wikipedia
// "2026 FIFA World Cup round of 32" / third-place combination table.
//
// The round-of-32 pairings are FIXED by group position, NOT re-seeded by
// strength. Eight group winners (A, B, D, E, G, I, K, L) each face a best
// third-placed team; which third they face depends on WHICH eight groups
// produce a qualifying third — that is the combination table below.
// ──────────────────────────────────────────────────────────────────────────

/** Group letters whose WINNER faces a best-third-placed team in the round of 32,
 *  in the column order used by FIFA's official combination table. value[i] of a
 *  WC_THIRD_COMBINATIONS entry is the group whose 3rd-placed team meets the
 *  winner of WC_WINNER_COLUMNS[i]. */
export const WC_WINNER_COLUMNS = ["A", "B", "D", "E", "G", "I", "K", "L"] as const;

/**
 * FIFA's allocation of the eight best third-placed teams to round-of-32 matches.
 * 495 = C(12,8) entries, one per possible set of eight groups whose third-placed
 * team qualifies.
 *
 *   Key:   the 8 qualifying group letters, sorted   (e.g. "EFGHIJKL").
 *   Value: the group each WC_WINNER_COLUMNS winner plays, same order
 *          (e.g. "EJIFHGLK" → winner A vs 3rd-of-E, winner B vs 3rd-of-J, …).
 *
 * Verified against the official table: every C(12,8) key present, each value is
 * a permutation of its key, and the 15 "still possible" rows matched exactly.
 */
export const WC_THIRD_COMBINATIONS: Record<string, string> = {
  "ABCDEFGH":"HGBCAFDE", "ABCDEFGI":"CGBDAFEI", "ABCDEFGJ":"CGBDAFEJ", "ABCDEFGK":"CGBDAFEK",
  "ABCDEFGL":"CGBDAFLE", "ABCDEFHI":"HEBCAFDI", "ABCDEFHJ":"HJBCAFDE", "ABCDEFHK":"HEBCAFDK",
  "ABCDEFHL":"HFBCADLE", "ABCDEFIJ":"CJBDAFEI", "ABCDEFIK":"CEBDAFIK", "ABCDEFIL":"CEBDAFLI",
  "ABCDEFJK":"CJBDAFEK", "ABCDEFJL":"CJBDAFLE", "ABCDEFKL":"CEBDAFLK", "ABCDEGHI":"HGBCADEI",
  "ABCDEGHJ":"HGBCADEJ", "ABCDEGHK":"HGBCADEK", "ABCDEGHL":"HGBCADLE", "ABCDEGIJ":"EGBCADIJ",
  "ABCDEGIK":"EGBCADIK", "ABCDEGIL":"EGBCADLI", "ABCDEGJK":"EGBCADJK", "ABCDEGJL":"EGBCADLJ",
  "ABCDEGKL":"EGBCADLK", "ABCDEHIJ":"HJBCADEI", "ABCDEHIK":"HEBCADIK", "ABCDEHIL":"HEBCADLI",
  "ABCDEHJK":"HJBCADEK", "ABCDEHJL":"HJBCADLE", "ABCDEHKL":"HEBCADLK", "ABCDEIJK":"EJBCADIK",
  "ABCDEIJL":"EJBCADLI", "ABCDEIKL":"EIBCADLK", "ABCDEJKL":"EJBCADLK", "ABCDFGHI":"HGBCAFDI",
  "ABCDFGHJ":"HGBCAFDJ", "ABCDFGHK":"HGBCAFDK", "ABCDFGHL":"CGBDAFLH", "ABCDFGIJ":"CGBDAFIJ",
  "ABCDFGIK":"CGBDAFIK", "ABCDFGIL":"CGBDAFLI", "ABCDFGJK":"CGBDAFJK", "ABCDFGJL":"CGBDAFLJ",
  "ABCDFGKL":"CGBDAFLK", "ABCDFHIJ":"HJBCAFDI", "ABCDFHIK":"HFBCADIK", "ABCDFHIL":"HFBCADLI",
  "ABCDFHJK":"HJBCAFDK", "ABCDFHJL":"CJBDAFLH", "ABCDFHKL":"HFBCADLK", "ABCDFIJK":"CJBDAFIK",
  "ABCDFIJL":"CJBDAFLI", "ABCDFIKL":"CIBDAFLK", "ABCDFJKL":"CJBDAFLK", "ABCDGHIJ":"HGBCADIJ",
  "ABCDGHIK":"HGBCADIK", "ABCDGHIL":"HGBCADLI", "ABCDGHJK":"HGBCADJK", "ABCDGHJL":"HGBCADLJ",
  "ABCDGHKL":"HGBCADLK", "ABCDGIJK":"CJBDAGIK", "ABCDGIJL":"CJBDAGLI", "ABCDGIKL":"IGBCADLK",
  "ABCDGJKL":"CJBDAGLK", "ABCDHIJK":"HJBCADIK", "ABCDHIJL":"HJBCADLI", "ABCDHIKL":"HIBCADLK",
  "ABCDHJKL":"HJBCADLK", "ABCDIJKL":"IJBCADLK", "ABCEFGHI":"HGBCAFEI", "ABCEFGHJ":"HGBCAFEJ",
  "ABCEFGHK":"HGBCAFEK", "ABCEFGHL":"HGBCAFLE", "ABCEFGIJ":"EGBCAFIJ", "ABCEFGIK":"EGBCAFIK",
  "ABCEFGIL":"EGBCAFLI", "ABCEFGJK":"EGBCAFJK", "ABCEFGJL":"EGBCAFLJ", "ABCEFGKL":"EGBCAFLK",
  "ABCEFHIJ":"HJBCAFEI", "ABCEFHIK":"HEBCAFIK", "ABCEFHIL":"HEBCAFLI", "ABCEFHJK":"HJBCAFEK",
  "ABCEFHJL":"HJBCAFLE", "ABCEFHKL":"HEBCAFLK", "ABCEFIJK":"EJBCAFIK", "ABCEFIJL":"EJBCAFLI",
  "ABCEFIKL":"EIBCAFLK", "ABCEFJKL":"EJBCAFLK", "ABCEGHIJ":"HJBCAGEI", "ABCEGHIK":"EGBCAHIK",
  "ABCEGHIL":"EGBCAHLI", "ABCEGHJK":"HJBCAGEK", "ABCEGHJL":"HJBCAGLE", "ABCEGHKL":"EGBCAHLK",
  "ABCEGIJK":"EJBCAGIK", "ABCEGIJL":"EJBCAGLI", "ABCEGIKL":"EGBAICLK", "ABCEGJKL":"EJBCAGLK",
  "ABCEHIJK":"EJBCAHIK", "ABCEHIJL":"EJBCAHLI", "ABCEHIKL":"EIBCAHLK", "ABCEHJKL":"EJBCAHLK",
  "ABCEIJKL":"EJBAICLK", "ABCFGHIJ":"HGBCAFIJ", "ABCFGHIK":"HGBCAFIK", "ABCFGHIL":"HGBCAFLI",
  "ABCFGHJK":"HGBCAFJK", "ABCFGHJL":"HGBCAFLJ", "ABCFGHKL":"HGBCAFLK", "ABCFGIJK":"CJBFAGIK",
  "ABCFGIJL":"CJBFAGLI", "ABCFGIKL":"IGBCAFLK", "ABCFGJKL":"CJBFAGLK", "ABCFHIJK":"HJBCAFIK",
  "ABCFHIJL":"HJBCAFLI", "ABCFHIKL":"HIBCAFLK", "ABCFHJKL":"HJBCAFLK", "ABCFIJKL":"IJBCAFLK",
  "ABCGHIJK":"HJBCAGIK", "ABCGHIJL":"HJBCAGLI", "ABCGHIKL":"IGBCAHLK", "ABCGHJKL":"HJBCAGLK",
  "ABCGIJKL":"IJBCAGLK", "ABCHIJKL":"IJBCAHLK", "ABDEFGHI":"HGBDAFEI", "ABDEFGHJ":"HGBDAFEJ",
  "ABDEFGHK":"HGBDAFEK", "ABDEFGHL":"HGBDAFLE", "ABDEFGIJ":"EGBDAFIJ", "ABDEFGIK":"EGBDAFIK",
  "ABDEFGIL":"EGBDAFLI", "ABDEFGJK":"EGBDAFJK", "ABDEFGJL":"EGBDAFLJ", "ABDEFGKL":"EGBDAFLK",
  "ABDEFHIJ":"HJBDAFEI", "ABDEFHIK":"HEBDAFIK", "ABDEFHIL":"HEBDAFLI", "ABDEFHJK":"HJBDAFEK",
  "ABDEFHJL":"HJBDAFLE", "ABDEFHKL":"HEBDAFLK", "ABDEFIJK":"EJBDAFIK", "ABDEFIJL":"EJBDAFLI",
  "ABDEFIKL":"EIBDAFLK", "ABDEFJKL":"EJBDAFLK", "ABDEGHIJ":"HJBDAGEI", "ABDEGHIK":"EGBDAHIK",
  "ABDEGHIL":"EGBDAHLI", "ABDEGHJK":"HJBDAGEK", "ABDEGHJL":"HJBDAGLE", "ABDEGHKL":"EGBDAHLK",
  "ABDEGIJK":"EJBDAGIK", "ABDEGIJL":"EJBDAGLI", "ABDEGIKL":"EGBAIDLK", "ABDEGJKL":"EJBDAGLK",
  "ABDEHIJK":"EJBDAHIK", "ABDEHIJL":"EJBDAHLI", "ABDEHIKL":"EIBDAHLK", "ABDEHJKL":"EJBDAHLK",
  "ABDEIJKL":"EJBAIDLK", "ABDFGHIJ":"HGBDAFIJ", "ABDFGHIK":"HGBDAFIK", "ABDFGHIL":"HGBDAFLI",
  "ABDFGHJK":"HGBDAFJK", "ABDFGHJL":"HGBDAFLJ", "ABDFGHKL":"HGBDAFLK", "ABDFGIJK":"FJBDAGIK",
  "ABDFGIJL":"FJBDAGLI", "ABDFGIKL":"IGBDAFLK", "ABDFGJKL":"FJBDAGLK", "ABDFHIJK":"HJBDAFIK",
  "ABDFHIJL":"HJBDAFLI", "ABDFHIKL":"HIBDAFLK", "ABDFHJKL":"HJBDAFLK", "ABDFIJKL":"IJBDAFLK",
  "ABDGHIJK":"HJBDAGIK", "ABDGHIJL":"HJBDAGLI", "ABDGHIKL":"IGBDAHLK", "ABDGHJKL":"HJBDAGLK",
  "ABDGIJKL":"IJBDAGLK", "ABDHIJKL":"IJBDAHLK", "ABEFGHIJ":"HJBFAGEI", "ABEFGHIK":"EGBFAHIK",
  "ABEFGHIL":"EGBFAHLI", "ABEFGHJK":"HJBFAGEK", "ABEFGHJL":"HJBFAGLE", "ABEFGHKL":"EGBFAHLK",
  "ABEFGIJK":"EJBFAGIK", "ABEFGIJL":"EJBFAGLI", "ABEFGIKL":"EGBAIFLK", "ABEFGJKL":"EJBFAGLK",
  "ABEFHIJK":"EJBFAHIK", "ABEFHIJL":"EJBFAHLI", "ABEFHIKL":"EIBFAHLK", "ABEFHJKL":"EJBFAHLK",
  "ABEFIJKL":"EJBAIFLK", "ABEGHIJK":"EJBAHGIK", "ABEGHIJL":"EJBAHGLI", "ABEGHIKL":"EGBAIHLK",
  "ABEGHJKL":"EJBAHGLK", "ABEGIJKL":"EJBAIGLK", "ABEHIJKL":"EJBAIHLK", "ABFGHIJK":"HJBFAGIK",
  "ABFGHIJL":"HJBFAGLI", "ABFGHIKL":"HGBAIFLK", "ABFGHJKL":"HJBFAGLK", "ABFGIJKL":"IJBFAGLK",
  "ABFHIJKL":"HJBAIFLK", "ABGHIJKL":"HJBAIGLK", "ACDEFGHI":"HGECAFDI", "ACDEFGHJ":"HGJCAFDE",
  "ACDEFGHK":"HGECAFDK", "ACDEFGHL":"HGFCADLE", "ACDEFGIJ":"CGJDAFEI", "ACDEFGIK":"CGEDAFIK",
  "ACDEFGIL":"CGEDAFLI", "ACDEFGJK":"CGJDAFEK", "ACDEFGJL":"CGJDAFLE", "ACDEFGKL":"CGEDAFLK",
  "ACDEFHIJ":"HJECAFDI", "ACDEFHIK":"HEFCADIK", "ACDEFHIL":"HEFCADLI", "ACDEFHJK":"HJECAFDK",
  "ACDEFHJL":"HJFCADLE", "ACDEFHKL":"HEFCADLK", "ACDEFIJK":"CJEDAFIK", "ACDEFIJL":"CJEDAFLI",
  "ACDEFIKL":"CEIDAFLK", "ACDEFJKL":"CJEDAFLK", "ACDEGHIJ":"HGJCADEI", "ACDEGHIK":"HGECADIK",
  "ACDEGHIL":"HGECADLI", "ACDEGHJK":"HGJCADEK", "ACDEGHJL":"HGJCADLE", "ACDEGHKL":"HGECADLK",
  "ACDEGIJK":"EGJCADIK", "ACDEGIJL":"EGJCADLI", "ACDEGIKL":"EGICADLK", "ACDEGJKL":"EGJCADLK",
  "ACDEHIJK":"HJECADIK", "ACDEHIJL":"HJECADLI", "ACDEHIKL":"HEICADLK", "ACDEHJKL":"HJECADLK",
  "ACDEIJKL":"EJICADLK", "ACDFGHIJ":"HGJCAFDI", "ACDFGHIK":"HGFCADIK", "ACDFGHIL":"HGFCADLI",
  "ACDFGHJK":"HGJCAFDK", "ACDFGHJL":"CGJDAFLH", "ACDFGHKL":"HGFCADLK", "ACDFGIJK":"CGJDAFIK",
  "ACDFGIJL":"CGJDAFLI", "ACDFGIKL":"CGIDAFLK", "ACDFGJKL":"CGJDAFLK", "ACDFHIJK":"HJFCADIK",
  "ACDFHIJL":"HJFCADLI", "ACDFHIKL":"HFICADLK", "ACDFHJKL":"HJFCADLK", "ACDFIJKL":"CJIDAFLK",
  "ACDGHIJK":"HGJCADIK", "ACDGHIJL":"HGJCADLI", "ACDGHIKL":"HGICADLK", "ACDGHJKL":"HGJCADLK",
  "ACDGIJKL":"IGJCADLK", "ACDHIJKL":"HJICADLK", "ACEFGHIJ":"HGJCAFEI", "ACEFGHIK":"HGECAFIK",
  "ACEFGHIL":"HGECAFLI", "ACEFGHJK":"HGJCAFEK", "ACEFGHJL":"HGJCAFLE", "ACEFGHKL":"HGECAFLK",
  "ACEFGIJK":"EGJCAFIK", "ACEFGIJL":"EGJCAFLI", "ACEFGIKL":"EGICAFLK", "ACEFGJKL":"EGJCAFLK",
  "ACEFHIJK":"HJECAFIK", "ACEFHIJL":"HJECAFLI", "ACEFHIKL":"HEICAFLK", "ACEFHJKL":"HJECAFLK",
  "ACEFIJKL":"EJICAFLK", "ACEGHIJK":"EGJCAHIK", "ACEGHIJL":"EGJCAHLI", "ACEGHIKL":"EGICAHLK",
  "ACEGHJKL":"EGJCAHLK", "ACEGIJKL":"EJICAGLK", "ACEHIJKL":"EJICAHLK", "ACFGHIJK":"HGJCAFIK",
  "ACFGHIJL":"HGJCAFLI", "ACFGHIKL":"HGICAFLK", "ACFGHJKL":"HGJCAFLK", "ACFGIJKL":"IGJCAFLK",
  "ACFHIJKL":"HJICAFLK", "ACGHIJKL":"HJICAGLK", "ADEFGHIJ":"HGJDAFEI", "ADEFGHIK":"HGEDAFIK",
  "ADEFGHIL":"HGEDAFLI", "ADEFGHJK":"HGJDAFEK", "ADEFGHJL":"HGJDAFLE", "ADEFGHKL":"HGEDAFLK",
  "ADEFGIJK":"EGJDAFIK", "ADEFGIJL":"EGJDAFLI", "ADEFGIKL":"EGIDAFLK", "ADEFGJKL":"EGJDAFLK",
  "ADEFHIJK":"HJEDAFIK", "ADEFHIJL":"HJEDAFLI", "ADEFHIKL":"HEIDAFLK", "ADEFHJKL":"HJEDAFLK",
  "ADEFIJKL":"EJIDAFLK", "ADEGHIJK":"EGJDAHIK", "ADEGHIJL":"EGJDAHLI", "ADEGHIKL":"EGIDAHLK",
  "ADEGHJKL":"EGJDAHLK", "ADEGIJKL":"EJIDAGLK", "ADEHIJKL":"EJIDAHLK", "ADFGHIJK":"HGJDAFIK",
  "ADFGHIJL":"HGJDAFLI", "ADFGHIKL":"HGIDAFLK", "ADFGHJKL":"HGJDAFLK", "ADFGIJKL":"IGJDAFLK",
  "ADFHIJKL":"HJIDAFLK", "ADGHIJKL":"HJIDAGLK", "AEFGHIJK":"EGJFAHIK", "AEFGHIJL":"EGJFAHLI",
  "AEFGHIKL":"EGIFAHLK", "AEFGHJKL":"EGJFAHLK", "AEFGIJKL":"EJIFAGLK", "AEFHIJKL":"EJIFAHLK",
  "AEGHIJKL":"EJIAHGLK", "AFGHIJKL":"HJIFAGLK", "BCDEFGHI":"CGBDHFEI", "BCDEFGHJ":"HGBCJFDE",
  "BCDEFGHK":"CGBDHFEK", "BCDEFGHL":"CGBDHFLE", "BCDEFGIJ":"CGBDJFEI", "BCDEFGIK":"CGBDEFIK",
  "BCDEFGIL":"CGBDEFLI", "BCDEFGJK":"CGBDJFEK", "BCDEFGJL":"CGBDJFLE", "BCDEFGKL":"CGBDEFLK",
  "BCDEFHIJ":"CJBDHFEI", "BCDEFHIK":"CEBDHFIK", "BCDEFHIL":"CEBDHFLI", "BCDEFHJK":"CJBDHFEK",
  "BCDEFHJL":"CJBDHFLE", "BCDEFHKL":"CEBDHFLK", "BCDEFIJK":"CJBDEFIK", "BCDEFIJL":"CJBDEFLI",
  "BCDEFIKL":"CEBDIFLK", "BCDEFJKL":"CJBDEFLK", "BCDEGHIJ":"HGBCJDEI", "BCDEGHIK":"EGBCHDIK",
  "BCDEGHIL":"EGBCHDLI", "BCDEGHJK":"HGBCJDEK", "BCDEGHJL":"HGBCJDLE", "BCDEGHKL":"EGBCHDLK",
  "BCDEGIJK":"EGBCJDIK", "BCDEGIJL":"EGBCJDLI", "BCDEGIKL":"EGBCIDLK", "BCDEGJKL":"EGBCJDLK",
  "BCDEHIJK":"EJBCHDIK", "BCDEHIJL":"EJBCHDLI", "BCDEHIKL":"EIBCHDLK", "BCDEHJKL":"EJBCHDLK",
  "BCDEIJKL":"EJBCIDLK", "BCDFGHIJ":"HGBCJFDI", "BCDFGHIK":"CGBDHFIK", "BCDFGHIL":"CGBDHFLI",
  "BCDFGHJK":"HGBCJFDK", "BCDFGHJL":"CGBDHFLJ", "BCDFGHKL":"CGBDHFLK", "BCDFGIJK":"CGBDJFIK",
  "BCDFGIJL":"CGBDJFLI", "BCDFGIKL":"CGBDIFLK", "BCDFGJKL":"CGBDJFLK", "BCDFHIJK":"CJBDHFIK",
  "BCDFHIJL":"CJBDHFLI", "BCDFHIKL":"CIBDHFLK", "BCDFHJKL":"CJBDHFLK", "BCDFIJKL":"CJBDIFLK",
  "BCDGHIJK":"HGBCJDIK", "BCDGHIJL":"HGBCJDLI", "BCDGHIKL":"HGBCIDLK", "BCDGHJKL":"HGBCJDLK",
  "BCDGIJKL":"IGBCJDLK", "BCDHIJKL":"HJBCIDLK", "BCEFGHIJ":"HGBCJFEI", "BCEFGHIK":"EGBCHFIK",
  "BCEFGHIL":"EGBCHFLI", "BCEFGHJK":"HGBCJFEK", "BCEFGHJL":"HGBCJFLE", "BCEFGHKL":"EGBCHFLK",
  "BCEFGIJK":"EGBCJFIK", "BCEFGIJL":"EGBCJFLI", "BCEFGIKL":"EGBCIFLK", "BCEFGJKL":"EGBCJFLK",
  "BCEFHIJK":"EJBCHFIK", "BCEFHIJL":"EJBCHFLI", "BCEFHIKL":"EIBCHFLK", "BCEFHJKL":"EJBCHFLK",
  "BCEFIJKL":"EJBCIFLK", "BCEGHIJK":"EJBCHGIK", "BCEGHIJL":"EJBCHGLI", "BCEGHIKL":"EGBCIHLK",
  "BCEGHJKL":"EJBCHGLK", "BCEGIJKL":"EJBCIGLK", "BCEHIJKL":"EJBCIHLK", "BCFGHIJK":"HGBCJFIK",
  "BCFGHIJL":"HGBCJFLI", "BCFGHIKL":"HGBCIFLK", "BCFGHJKL":"HGBCJFLK", "BCFGIJKL":"IGBCJFLK",
  "BCFHIJKL":"HJBCIFLK", "BCGHIJKL":"HJBCIGLK", "BDEFGHIJ":"HGBDJFEI", "BDEFGHIK":"EGBDHFIK",
  "BDEFGHIL":"EGBDHFLI", "BDEFGHJK":"HGBDJFEK", "BDEFGHJL":"HGBDJFLE", "BDEFGHKL":"EGBDHFLK",
  "BDEFGIJK":"EGBDJFIK", "BDEFGIJL":"EGBDJFLI", "BDEFGIKL":"EGBDIFLK", "BDEFGJKL":"EGBDJFLK",
  "BDEFHIJK":"EJBDHFIK", "BDEFHIJL":"EJBDHFLI", "BDEFHIKL":"EIBDHFLK", "BDEFHJKL":"EJBDHFLK",
  "BDEFIJKL":"EJBDIFLK", "BDEGHIJK":"EJBDHGIK", "BDEGHIJL":"EJBDHGLI", "BDEGHIKL":"EGBDIHLK",
  "BDEGHJKL":"EJBDHGLK", "BDEGIJKL":"EJBDIGLK", "BDEHIJKL":"EJBDIHLK", "BDFGHIJK":"HGBDJFIK",
  "BDFGHIJL":"HGBDJFLI", "BDFGHIKL":"HGBDIFLK", "BDFGHJKL":"HGBDJFLK", "BDFGIJKL":"IGBDJFLK",
  "BDFHIJKL":"HJBDIFLK", "BDGHIJKL":"HJBDIGLK", "BEFGHIJK":"EJBFHGIK", "BEFGHIJL":"EJBFHGLI",
  "BEFGHIKL":"EGBFIHLK", "BEFGHJKL":"EJBFHGLK", "BEFGIJKL":"EJBFIGLK", "BEFHIJKL":"EJBFIHLK",
  "BEGHIJKL":"EJIBHGLK", "BFGHIJKL":"HJBFIGLK", "CDEFGHIJ":"CGJDHFEI", "CDEFGHIK":"CGEDHFIK",
  "CDEFGHIL":"CGEDHFLI", "CDEFGHJK":"CGJDHFEK", "CDEFGHJL":"CGJDHFLE", "CDEFGHKL":"CGEDHFLK",
  "CDEFGIJK":"CGEDJFIK", "CDEFGIJL":"CGEDJFLI", "CDEFGIKL":"CGEDIFLK", "CDEFGJKL":"CGEDJFLK",
  "CDEFHIJK":"CJEDHFIK", "CDEFHIJL":"CJEDHFLI", "CDEFHIKL":"CEIDHFLK", "CDEFHJKL":"CJEDHFLK",
  "CDEFIJKL":"CJEDIFLK", "CDEGHIJK":"EGJCHDIK", "CDEGHIJL":"EGJCHDLI", "CDEGHIKL":"EGICHDLK",
  "CDEGHJKL":"EGJCHDLK", "CDEGIJKL":"EGICJDLK", "CDEHIJKL":"EJICHDLK", "CDFGHIJK":"CGJDHFIK",
  "CDFGHIJL":"CGJDHFLI", "CDFGHIKL":"CGIDHFLK", "CDFGHJKL":"CGJDHFLK", "CDFGIJKL":"CGIDJFLK",
  "CDFHIJKL":"CJIDHFLK", "CDGHIJKL":"HGICJDLK", "CEFGHIJK":"EGJCHFIK", "CEFGHIJL":"EGJCHFLI",
  "CEFGHIKL":"EGICHFLK", "CEFGHJKL":"EGJCHFLK", "CEFGIJKL":"EGICJFLK", "CEFHIJKL":"EJICHFLK",
  "CEGHIJKL":"EJICHGLK", "CFGHIJKL":"HGICJFLK", "DEFGHIJK":"EGJDHFIK", "DEFGHIJL":"EGJDHFLI",
  "DEFGHIKL":"EGIDHFLK", "DEFGHJKL":"EGJDHFLK", "DEFGIJKL":"EGIDJFLK", "DEFHIJKL":"EJIDHFLK",
  "DEGHIJKL":"EJIDHGLK", "DFGHIJKL":"HGIDJFLK", "EFGHIJKL":"EJIFHGLK",
};

/**
 * Resolve which third-placed group each winner-column faces, given the eight
 * group letters whose third-placed team qualified. Returns null when the set is
 * not one of the 495 valid eight-of-twelve combinations.
 */
export function assignThirdPlaced(
  qualifyingThirdGroups: string[],
): Record<string, string> | null {
  if (qualifyingThirdGroups.length !== WC_WINNER_COLUMNS.length) return null;
  const key = [...qualifyingThirdGroups].sort().join("");
  const assignment = WC_THIRD_COMBINATIONS[key];
  if (!assignment) return null;
  const out: Record<string, string> = {};
  WC_WINNER_COLUMNS.forEach((col, i) => {
    out[col] = assignment[i];
  });
  return out;
}

/**
 * The official bracket, laid out as a no-crossing tree (depth-first leaf order)
 * so the connectors render cleanly while preserving the exact FIFA matchup tree.
 * Tie ids are the official match numbers (M73–M103). Round-of-32 ties carry the
 * fixed seed slots; later rounds resolve from their feeders.
 *
 *   { winner: "A" }   → winner of Group A
 *   { runnerUp: "A" } → runner-up of Group A
 *   { thirdFor: "A" } → the best third assigned to winner A by the combo table
 */
export const WC_BRACKET_TEMPLATE: BracketTemplate = {
  rounds: {
    LAST_32: [
      { id: "M74", homeSlot: { winner: "E" }, awaySlot: { thirdFor: "E" } },
      { id: "M77", homeSlot: { winner: "I" }, awaySlot: { thirdFor: "I" } },
      { id: "M73", homeSlot: { runnerUp: "A" }, awaySlot: { runnerUp: "B" } },
      { id: "M75", homeSlot: { winner: "F" }, awaySlot: { runnerUp: "C" } },
      { id: "M76", homeSlot: { winner: "C" }, awaySlot: { runnerUp: "F" } },
      { id: "M78", homeSlot: { runnerUp: "E" }, awaySlot: { runnerUp: "I" } },
      { id: "M79", homeSlot: { winner: "A" }, awaySlot: { thirdFor: "A" } },
      { id: "M80", homeSlot: { winner: "L" }, awaySlot: { thirdFor: "L" } },
      { id: "M83", homeSlot: { runnerUp: "K" }, awaySlot: { runnerUp: "L" } },
      { id: "M84", homeSlot: { winner: "H" }, awaySlot: { runnerUp: "J" } },
      { id: "M81", homeSlot: { winner: "D" }, awaySlot: { thirdFor: "D" } },
      { id: "M82", homeSlot: { winner: "G" }, awaySlot: { thirdFor: "G" } },
      { id: "M86", homeSlot: { winner: "J" }, awaySlot: { runnerUp: "H" } },
      { id: "M88", homeSlot: { runnerUp: "D" }, awaySlot: { runnerUp: "G" } },
      { id: "M85", homeSlot: { winner: "B" }, awaySlot: { thirdFor: "B" } },
      { id: "M87", homeSlot: { winner: "K" }, awaySlot: { thirdFor: "K" } },
    ],
    LAST_16: [
      { id: "M89", feederHome: "M74", feederAway: "M77" },
      { id: "M90", feederHome: "M73", feederAway: "M75" },
      { id: "M93", feederHome: "M76", feederAway: "M78" },
      { id: "M94", feederHome: "M79", feederAway: "M80" },
      { id: "M91", feederHome: "M83", feederAway: "M84" },
      { id: "M92", feederHome: "M81", feederAway: "M82" },
      { id: "M95", feederHome: "M86", feederAway: "M88" },
      { id: "M96", feederHome: "M85", feederAway: "M87" },
    ],
    QUARTER_FINALS: [
      { id: "M97", feederHome: "M89", feederAway: "M90" },
      { id: "M98", feederHome: "M93", feederAway: "M94" },
      { id: "M99", feederHome: "M91", feederAway: "M92" },
      { id: "M100", feederHome: "M95", feederAway: "M96" },
    ],
    SEMI_FINALS: [
      { id: "M101", feederHome: "M97", feederAway: "M98" },
      { id: "M102", feederHome: "M99", feederAway: "M100" },
    ],
    FINAL: [
      { id: "M103", feederHome: "M101", feederAway: "M102" },
    ],
  },
};
